"""Host-only configuration: monitor state, alert settings, Mailtrap."""
import os
from pathlib import Path

CHECK_INTERVAL = 60  # monitor poll interval, seconds

MONITOR_STATE_FILE = Path.home() / ".aws_slurm_like_monitor_state.json"

MAILTRAP_TOKEN = os.getenv("AWSQUEUEENGINE_MAILTRAP_TOKEN", "").strip()
MAILTRAP_SENDER_EMAIL = os.getenv("AWSQUEUEENGINE_MAILTRAP_SENDER_EMAIL", "").strip()
MAILTRAP_SENDER_NAME = os.getenv("AWSQUEUEENGINE_MAILTRAP_SENDER_NAME", "AWSQueueEngine").strip()
MAILTRAP_CATEGORY = os.getenv("AWSQUEUEENGINE_MAILTRAP_CATEGORY", "Queue Monitor").strip()

ALERT_DAILY_EMAIL_LIMIT = int(os.getenv("AWSQUEUEENGINE_ALERT_DAILY_EMAIL_LIMIT", "150"))
JOB_FAIL_ALERT_COOLDOWN_SECONDS = int(os.getenv("AWSQUEUEENGINE_JOB_FAIL_ALERT_COOLDOWN_SECONDS", "900"))
MAX_SUBMIT_FAILURES = int(os.getenv("AWSQUEUEENGINE_MAX_SUBMIT_FAILURES", "3"))
HOST_STORAGE_COOLDOWN_SECONDS = int(os.getenv("AWSQUEUEENGINE_HOST_STORAGE_COOLDOWN_SECONDS", "7200"))
HOST_TRANSPORT_COOLDOWN_SECONDS = int(os.getenv("AWSQUEUEENGINE_HOST_TRANSPORT_COOLDOWN_SECONDS", "600"))
